### PR TITLE
Use pure setuptools instead of pbr

### PR DESCRIPTION
**Pull request by temujin**
Remove pbr from requirements

### CODE REVIEW

**Comment by boris-42** [comment]
Works well in virtualenv. 

But doesn't work when installed in system: 

19:06:11 boris ~/Documents/os/my/profimp > sudo python setup.py install
running install
Checking .pth file support in /Library/Python/2.7/site-packages/
/usr/bin/python -E -c pass
TEST PASSED: /Library/Python/2.7/site-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing profimp.egg-info/PKG-INFO
writing top-level names to profimp.egg-info/top_level.txt
writing dependency_links to profimp.egg-info/dependency_links.txt
writing pbr to profimp.egg-info/pbr.json
reading manifest file 'profimp.egg-info/SOURCES.txt'
writing manifest file 'profimp.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.10-intel/egg
running install_lib
running build_py
creating build/bdist.macosx-10.10-intel/egg
creating build/bdist.macosx-10.10-intel/egg/profimp
copying build/lib/profimp/**init**.py -> build/bdist.macosx-10.10-intel/egg/profimp
copying build/lib/profimp/main.py -> build/bdist.macosx-10.10-intel/egg/profimp
copying build/lib/profimp/reports.py -> build/bdist.macosx-10.10-intel/egg/profimp
creating build/bdist.macosx-10.10-intel/egg/profimp/templates
copying build/lib/profimp/templates/report.tpl -> build/bdist.macosx-10.10-intel/egg/profimp/templates
copying build/lib/profimp/tracer.py -> build/bdist.macosx-10.10-intel/egg/profimp
byte-compiling build/bdist.macosx-10.10-intel/egg/profimp/**init**.py to **init**.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/profimp/main.py to main.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/profimp/reports.py to reports.pyc
byte-compiling build/bdist.macosx-10.10-intel/egg/profimp/tracer.py to tracer.pyc
installing package data to build/bdist.macosx-10.10-intel/egg
running install_data
creating build/bdist.macosx-10.10-intel/egg/EGG-INFO
copying profimp.egg-info/PKG-INFO -> build/bdist.macosx-10.10-intel/egg/EGG-INFO
copying profimp.egg-info/SOURCES.txt -> build/bdist.macosx-10.10-intel/egg/EGG-INFO
copying profimp.egg-info/dependency_links.txt -> build/bdist.macosx-10.10-intel/egg/EGG-INFO
copying profimp.egg-info/pbr.json -> build/bdist.macosx-10.10-intel/egg/EGG-INFO
copying profimp.egg-info/top_level.txt -> build/bdist.macosx-10.10-intel/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
profimp.reports: module references **file**
profimp.tracer: module references **file**
creating 'dist/profimp-0.0.3-py2.7.egg' and adding 'build/bdist.macosx-10.10-intel/egg' to it
removing 'build/bdist.macosx-10.10-intel/egg' (and everything under it)
Processing profimp-0.0.3-py2.7.egg
creating /Library/Python/2.7/site-packages/profimp-0.0.3-py2.7.egg
Extracting profimp-0.0.3-py2.7.egg to /Library/Python/2.7/site-packages
Adding profimp 0.0.3 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/profimp-0.0.3-py2.7.egg
Processing dependencies for profimp==0.0.3
Finished processing dependencies for profimp==0.0.3
19:06:16 boris ~/Documents/os/my/profimp > cd ..
19:06:19 boris ~/Documents/os/my > cd ..
19:06:22 boris ~/Documents/os > profimp
-bash: profimp: command not found

**Comment by temujin** [comment]
> > But doesn't work when installed in system:

That's confusing, cause:

$ git clone git@github.com:temujin/profimp
$ cd profimp/
$ sudo pip install .
Unpacking /tmp/profimp
  Running setup.py (path:/tmp/pip-nGMNHA-build/setup.py) egg_info for package from file:///tmp/profimp

Installing collected packages: profimp
  Running setup.py install for profimp

Successfully installed profimp
Cleaning up...

$ whereis profimp
profimp: /usr/bin/profimp

$ profimp

```
Profimp allows you to trace imports of your code.

This lib should be used to simplify optimization of imports in your code.
At least you will find what consumes the most part of time and do the
right decisions.

Syntax:
    profimp [import_module_line] [--html]

Samples:
    profimp "import collections"

    profimp "from somemoudle import something"

    prpfimp --html "import multiprocessing"
```

$ sudo pip uninstall profimp
$ sudo rm -rf /usr/bin/profimp

$ file /usr/bin/profimp
/usr/bin/profimp: cannot open `/usr/bin/profimp' (No such file or directory)

$ sudo python setup.py install
running install
/usr/lib64/python2.7/site-packages/pkg_resources/**init**.py:2510: PEP440Warning: 'jedi (0.8.1-final0)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
running bdist_egg
running egg_info
writing profimp.egg-info/PKG-INFO
writing top-level names to profimp.egg-info/top_level.txt
writing dependency_links to profimp.egg-info/dependency_links.txt
reading manifest file 'profimp.egg-info/SOURCES.txt'
writing manifest file 'profimp.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/profimp
copying build/lib/profimp/**init**.py -> build/bdist.linux-x86_64/egg/profimp
copying build/lib/profimp/main.py -> build/bdist.linux-x86_64/egg/profimp
copying build/lib/profimp/reports.py -> build/bdist.linux-x86_64/egg/profimp
copying build/lib/profimp/tracer.py -> build/bdist.linux-x86_64/egg/profimp
byte-compiling build/bdist.linux-x86_64/egg/profimp/**init**.py to **init**.pyc
byte-compiling build/bdist.linux-x86_64/egg/profimp/main.py to main.pyc
byte-compiling build/bdist.linux-x86_64/egg/profimp/reports.py to reports.pyc
byte-compiling build/bdist.linux-x86_64/egg/profimp/tracer.py to tracer.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
copying bin/profimp -> /usr/bin
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying profimp.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying profimp.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying profimp.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying profimp.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
profimp.tracer: module references **file**
profimp.reports: module references **file**
creating 'dist/profimp-0.0.3-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing profimp-0.0.3-py2.7.egg
creating /usr/lib64/python2.7/site-packages/profimp-0.0.3-py2.7.egg
Extracting profimp-0.0.3-py2.7.egg to /usr/lib64/python2.7/site-packages
Adding profimp 0.0.3 to easy-install.pth file

Installed /usr/lib64/python2.7/site-packages/profimp-0.0.3-py2.7.egg
Processing dependencies for profimp==0.0.3
Finished processing dependencies for profimp==0.0.3

$ file /usr/bin/profimp
/usr/bin/profimp: Python script, ASCII text executable

$ profimp

```
Profimp allows you to trace imports of your code.

This lib should be used to simplify optimization of imports in your code.
At least you will find what consumes the most part of time and do the
right decisions.

Syntax:
    profimp [import_module_line] [--html]

Samples:
    profimp "import collections"

    profimp "from somemoudle import something"

    prpfimp --html "import multiprocessing"
```

**Comment by boris-42** [comment]
Checked few times and seems like it doesn't work on MacOS

**Comment by michaelkuty** [comment]
:-1:

**Pull request closed without merging**
