### PR TITLE
Fix badge and code highlighting

### PR DESCRIPTION
**Pull request by flying-sheep**

### CODE REVIEW

**Comment by boris-42** [comment]
Thanks for commit, seems like I will need to update a bit CI to get this merged

**Comment by flying-sheep** [comment]
Well, you can merge it now, it doesn’t touch anything the covered by the CI.

Just make your own PR to fix the CI independently.

**Comment by boris-42** [comment]
fair enough

**Comment by flying-sheep** [comment]
Great, thank you!

**Pull request merged**
